### ISSUE TITLE
Estimated release date for compatibility with Moodle v3.11

### ISSUE THREAD

**Issue by eurecomphil** [UbiCastTeam/moodle-mod_ubicast#11]
Dear all,
First of all, thank you for your module.
Are you able to tell me when your module will be compatible with Moodle v3.11 ?
I was upgrading my Moodle this morning to v3.11 and found out that your module was not yet compatible.
Thank you very much,
Regards,
Philippe Foubert, EURECOM

**Comment by sdiemer** [comment]
Hello,

The plugins are already compatible.
I updated the information on the moodle.org site. It was not possible to set our plugins as compatible with Moodle 3.11 before it was released as stable.

Regards
