### ISSUE TITLE
Any chances to have tags or branches related to plugin or Moodle version ?

### ISSUE THREAD

**Issue by leManu** [UbiCastTeam/moodle-mod_ubicast#15]
Hi there,

We are currently using Moodle 3.11 in production with moodle-mod_ubicast. We are now having difficulty redeploying our Moodle instance, as there are no specific tags or branches for our version of Moodle in this repository.

Is it possible to create tags or branches corresponding to the different versions of the plugin by indicating for each the compatibility with the versions of Moodle?

In fact it seems that we have to base ourselves on commit e0524c0 to pull the correct version of the plugin for our Moodle version, but it would be easier to have specific tags...

**Comment by sdiemer** [comment]
Hello,

I just added branches for each change of required Moodle version.
You should use the branch moodle-3.7+ for Moodle 3.11.
You can view the branches location in the commits graph:
https://github.com/UbiCastTeam/moodle-mod_ubicast/network
I will do the same in the other plugins.

Regards

**Comment by leManu** [comment]
Great, thanks alot !
