### ISSUE TITLE
https://moodle.org/plugins/mod_ubicast doesn't work

### ISSUE THREAD

**Issue by Jarvil** [UbiCastTeam/moodle-mod_ubicast#7]
Hello,

Why doesn't

https://moodle.org/plugins/mod_ubicast

 work? @sdiemer

**Comment by sdiemer** [comment]
Hello,
Can you explain what is not working exactly ?
Could you create a ticket on https://panel.ubicast.eu (please indicate your UbiCast system serial number in the ticket) ?
Regards

**Comment by Jarvil** [comment]
Hello,

You are hosting this plugin for Moodle at moodle.org but the URL you have provided in:

https://moodle.org/plugins/mod_easycastms

that points to:
https://moodle.org/plugins/mod_ubicast

doesn't work

**Comment by sdiemer** [comment]
Hello,
Yes, it is because the plugin is waiting for approval on moodle.org. It is in this status for more than 2 months now.
Regards
