### ISSUE TITLE
error in function ubicast_user_complete

### ISSUE THREAD

**Issue by ldumorti** [UbiCastTeam/moodle-mod_ubicast#8]
The log table is not log but logstore_standard_log.
So request 
if ($logs = $DB->get_records('log', array('userid' => $user->id, 'module' => 'ubicast',
                                              'action' => 'view', 'info' => $ubicastresource->id), 'time ASC')) {
should be
if ($logs = $DB->get_records('logstore_standard_log', array('userid' => $user->id, 'component' => 'mod_ubicast',
                                              'action' => 'viewed', 'objectid' => $ubicastresource->id), 'timecreated ASC')) {

and since time is not a column of this stable, instruction 
 echo "$strnumviews - $strmostrecently ".userdate($lastlog->time);
should now be 
echo "$strnumviews - $strmostrecently ".userdate($lastlog->timecreated);

**Comment by fthiery** [comment]
Hi

Thanks for the report, would you mind to submit a pull request ?
